# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: "**/*.csproj"
  tests: "**/Tests.csproj"
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: Install .NET Core 3.0 SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.102'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
  displayName: Restore

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(tests)'
  displayName: Test